### ISSUE TITLE
Fail to start container when using both a PVC and an external secret resource

### ISSUE THREAD

**Issue by nmaupu** [Koenkk/zigbee2mqtt-chart#24]
Hi !

When using a PVC and a custom secret file, the container does not start.

values.yaml:

```yaml
statefulset:
  storage:
    enabled: true
    size: 1Gi
    storageClassName: openebs-hostpath
  secrets:
    name: zigbee2mqtt
```

Results in the following error:

```
Warning  Failed     14s (x2 over 15s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/d7125aac-89ac-4b41-9049-7523d4bed216/volume-subpaths/secrets-volume/zigbee2mqtt/3" to rootfs at "/app/data/secret.yaml": mount src=/var/lib/kubelet/pods/d7125aac-89ac-4b41-9049-7523d4bed216/volume-subpaths/secrets-volume/zigbee2mqtt/3, dst=/app/data/secret.yaml, dstFd=/proc/thread-self/fd/7, flags=0x5001: not a directory

```

Might be because `/app/data` does not exist when mounting secret resource. If I use `storage.enabled: false`, it starts ok and work as expected. The only problem is my devices need to be paired again...

**Comment by nmaupu** [comment]
ok, one solution would be to mount the secret file outside of the data dir and making a symlink as an init container.
I tested that successfully in my lab.

I can work a PR, just let me know. In the meantime, I will be forking.

**Comment by champloo** [comment]
@nmaupu I had the same issue today. In my case it turned out that my PVC already had a `secret.yaml` in it but it was a directory and not a file. So it was conflicting with the creation of the `secret.yaml` file.

In my case the directory got created during a previous run when I had my secrets defined differently and thus it ended up creating a `secrets.yaml` directory. Once I fixed the secrets definition to just generate a single file it started to give me that error.

I fixed it by mounting the PVC and deleting the directory. From there it worked fine.

Just for anyone else hitting the issue with secrets. I originally had  secrets defined like this, which created an empty `secrets.yaml` directory in `/app/data`

```
apiVersion: v1
kind: Secret
metadata:
    name: z2m-secret
    namespace: zigbee2mqtt
type: Opaque
stringData:
       auth_token:  token
       mqtt_password: password
       mqtt_user: user
       network_key: key
```

Once I changed it to this it created a file instead

```
apiVersion: v1
kind: Secret
metadata:
    name: z2m-secret
    namespace: zigbee2mqtt
type: Opaque
stringData:
      secret.yaml: |-
            auth_token:  token
             mqtt_password: password
             mqtt_user: user
             network_key: key
```
